- hosts: localhost
  gather_facts: false
  roles:
    # - rubrik-devops.rubrik-cloudon
    - { role: '/Users/drew_russell/Google Drive/Development/ansible-role-rubrik-cloudout' }
  vars:
    s3_bucket_name: "ansible-rubrik-cloudout-video-demo"
    aws_region: us-west-1 # US West (N. California)
    create_new_user: false
    iam_user: ansible-tower

    